// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"nunu/internal/handler"
	"nunu/internal/repository"
	"nunu/internal/server"
	"nunu/internal/service"
	"nunu/pkg/app"
	"nunu/pkg/embedding"
	"nunu/pkg/log"
	"nunu/pkg/server/http"
	"nunu/pkg/slackclient"

	"github.com/spf13/viper"
)

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	db := repository.NewDB(viperViper, logger)
	queryDB := repository.NewQueryDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	_ = repository.NewTransaction(repositoryRepository)
	memoryRepo := repository.NewMemoryRepository(db)
	knowledgeRepo := repository.NewKnowledgeRepository(db)
	convRepo := repository.NewConversationRepository(db)
	queryEngine := repository.NewPostgresQueryEngine(queryDB)

	embClient := embedding.NewClient(viperViper)
	slackClient := slackclient.NewClient(viperViper, logger.Logger)

	_ = service.NewService(logger)
	memorySvc := service.NewMemoryService(memoryRepo, embClient, logger)
	knowledgeSvc := service.NewKnowledgeService(knowledgeRepo, embClient, logger)
	querySvc := service.NewQueryService(queryEngine, logger, viperViper.GetInt("agent.max_query_rows"))
	csvSvc := service.NewCSVService(queryEngine, logger, viperViper.GetString("csv.storage_path"), viperViper.GetString("csv.base_url"))
	agentSvc := service.NewAgentService(viperViper, logger, memorySvc, knowledgeSvc, querySvc, csvSvc, convRepo)
	slackSvc := service.NewSlackService(slackClient, logger)

	_ = handler.NewHandler(logger)
	slackHandler := handler.NewSlackHandler(slackClient, agentSvc, slackSvc, logger)

	httpServer := server.NewHTTPServer(viperViper, logger)
	slackServer := server.NewSlackServer(slackClient, slackHandler, logger)

	appApp := app.NewApp(
		app.WithServer(httpServer, slackServer),
		app.WithName("nunu-agent"),
	)
	return appApp, func() {
	}, nil
}

// Keep http import used
var _ *http.Server
